language: ruby
rvm:
- 2.1.2
script:
- xvfb-run bundle exec rake spec
before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'create database test;' -U postgres
- ! 'RAILS_ENV=test bundle exec rake db:schema:load || :'
addons:
  firefox: "35.0.1"
  postgresql: "9.3"
