language: ruby
sudo: false
cache: bundler
rvm:
  - 2.3.0
script:
  - bundle exec rake spec
  - bundle exec teaspoon
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database test;' -U postgres
  - bundle exec rake db:migrate
addons:
  postgresql: "9.3"
  code_climate:
    repo_token: 284c330b001fc405fe9b1c8a013ebaed90e6f81b0318b2e3d0df66559dd0eb3e
env:
  FOG_DIRECTORY=empirical-core-travis-test
  PROGRESS_REPORT_FOG_DIRECTORY=empirical-progress-report-travis-test
