# NB: if using create options, include OPTIONS(), e.g.
# create_options: "OPTIONS(enable_refresh = true)"
default:
  active_classroom_stubs_view:
    dataset: 'lms'
    name: 'active_classroom_stubs_view'
    name_fallback: 'active_classroom_stubs_local'
    sql: 'active_classroom_stubs_view.sql'
  active_classroom_unit_stubs_view:
    dataset: 'lms'
    name: 'active_classroom_unit_stubs_view'
    name_fallback: 'active_classroom_unit_stubs_local'
    sql: 'active_classroom_unit_stubs_view.sql'
  active_user_names_view:
    dataset: 'lms'
    name: 'active_user_names_view'
    name_fallback: 'active_user_names_local'
    sql: 'active_user_names_view.sql'
  pre_post_diagnostic_skill_group_performance_view:
    dataset: 'lms'
    name: 'pre_post_diagnostic_skill_group_performance_view'
    name_fallback: 'pre_post_diagnostic_skill_performance_local'
    sql: 'pre_post_diagnostic_skill_group_performance_view.sql'
    create_options: "OPTIONS(allow_non_incremental_definition = true, enable_refresh = true, max_staleness = INTERVAL '8' HOUR, refresh_interval_minutes = 360)"
  recommendation_activity_session_stubs_view:
    dataset: 'lms'
    name: 'recommendation_activity_session_stubs_view'
    name_fallback: 'recommendation_activity_session_stubs_local'
    sql: 'recommendation_activity_session_stubs_view.sql'
  recommendation_count_rollup_view:
    dataset: 'lms'
    name: 'recommendation_count_rollup_view'
    name_fallback: 'recommendation_count_rollup_local'
    sql: 'recommendation_count_rollup_view.sql'
    create_options: "OPTIONS (enable_refresh = true, refresh_interval_minutes = 360, max_staleness = INTERVAL '8' HOUR, allow_non_incremental_definition = true)"
  reporting_sessions_view:
    dataset: 'lms'
    name: 'recent_reporting_sessions_view'
    name_fallback: 'recent_reporting_sessions_local'
    sql: 'reporting_sessions_view.sql'
  school_classroom_teachers_view:
    dataset: 'lms'
    name: 'school_classroom_teachers_view'
    name_fallback: 'school_classroom_teachers_local'
    sql: 'school_classroom_teachers_view.sql'
